services:
  backend:
    build:
      context: ../backend
    container_name: gowords-backend-dev
    ports:
      - "8081:8080"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  frontend:
    build:
      context: ../frontend
      args:
        - VITE_WS_BASE_URL=ws://localhost:8081
    container_name: gowords-frontend-dev
    ports:
      - "5173:3000"

  redis:
    container_name: redis
    image: redis:7
    ports:
      - "6380:6379"
    volumes:
      - redis_volume:/data

volumes:
  redis_volume:
